[package]
name = "passert_test"
version = "0.2.0"
authors = ["Manuel Woelker <github@manuel.woelker.org>"]

[dependencies.passert_macros]
path = "../passert_macros"

[dependencies.passert]
path = ".."
